name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:

  test:
    name: R
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [ ubuntu-latest ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install bcftools
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install bcftools build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev libzmq3-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libcurl4-openssl-dev libxml2-dev libfontconfig1-dev

      - name: Install package
        run: |
          dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE)
          .libPaths(Sys.getenv("R_LIBS_USER")) 
          install.packages("devtools")
          devtools::install("lostruct")
        shell: Rscript {0}

      - name: Run tests
        run: |
          res=devtools::test("lostruct")
          df=as.data.frame(res)
          if(sum(df$failed) > 0 || any(df$error)) {q(status=1)}
        shell: Rscript {0}
